package com.altice.salescommission.queries;

public interface PersonalInfoQueries {
	
	public final String GET_PAYROLL_CALENDAR_LIST = "select distinct calendar_type  from c_comm_calendar_type ccct where active_flag ='Active'";
	
	public final String FILTER_BY_EMPID_ROLE = "select * from c_employee_master cem where profile_status ='complete' and employee_id =? order by effective_date desc,case when user_role ='Sales Representative' then 1 when user_role ='Supervisor' then 2 else 3 end  desc limit 1";
	
	public final String FILTER_BY_EMPID_ROLE_IMPERSONATE = "select max(cem.effective_date) effective_date,sc_emp_id ,employee_id ,sales_rep_id,supervisor_id  ,(SELECT concat(u2.first_name,' ', u2.last_name) "
			+ "FROM c_employee_master u2 where u2.employee_id  = cem.supervisor_id limit 1) supervisor_name "
			+ "from c_employee_master cem where profile_status ='complete' and employee_id =? and user_role=? "
			+ "group by sc_emp_id ,employee_id ,sales_rep_id,supervisor_id";

	public final String GET_PersonalInfoFields = "select field_name,field_value,description from c_translate_master ctm  "
			+ "where field_name  in ('Sales Channel','User Type','Sales Rep Type','PayrollCalendar','Language') and effective_status = 'Y' order by description";

	public final String GET_CommPlans = "select distinct comm_plan_id ,concat(comm_plan,' - ',comm_plan_id) comm_plan from c_comm_plan_master  ccpm where active_flag='Y' order by comm_plan";

	public final String GET_UserInfo = "select * from c_employee_master cem where ";

	public final String FIND_COMPLETED_PROFILES_DUMMY = "select DISTINCT ON(cem.network_id) network_id,*,concat(TO_CHAR(cem.effective_date, 'YYYY/MM/DD'),'-',"
			+ "TO_CHAR(cem.soft_termination_date, 'YYYY/MM/DD')) activeCommPeriod ,ccpm.comm_plan,concat(cem.last_name,', ',first_name,', ',middle_name) as empname "
			+ "from c_employee_master cem "
			+ "left join c_comm_plan_master ccpm on cem.comm_plan_id = ccpm.comm_plan_id "
			+ "	where cem.profile_status = 'complete' and cem.network_id='abiradar' order by cem.network_id desc,cem.sc_emp_id desc ";

	public final String FIND_PERSONNEL_SEARCH_REPORT = "WITH enrollments AS (  SELECT DISTINCT cem.sc_emp_id,cem.first_name || ' ' || cem.last_name as name, cem.network_id ,cem.employee_id,"
			+ "cem.email_address,cem.calendar_type,cem.created_by,cem.created_dt,cem.operator_id\r\n"
			+ ", cem.comm_plan_id,cem.supervisor_ID,cem.user_role,cem.user_type,cem.first_name ,cem.middle_name,cem.last_name ,cem.soft_termination_date,cem.profile_status,cem.sales_rep_channel,cem.sales_rep_id,"
			+ "cem.effective_date,to_char(cem.effective_date,'MM-DD-YYYY') edate,"
			+ "cem.sales_rep_type,(SELECT concat(u2.first_name,',', u2.last_name  ,'-',u2.employee_id) FROM c_employee_master u2 where u2.employee_id  = cem.supervisor_id limit 1) supervisor_name "
			+ "FROM c_employee_master cem where cem.comm_plan_id IS NOT NULL AND cem.effective_date IS NOT null  "
			+ "			       and cem.effective_date = (select max(cem1.effective_date) from c_employee_master cem1 where cem.sc_emp_id = cem1.sc_emp_id and cem1.profile_status ='complete' and cem1.effective_date <= current_date )\r\n"
			+ "			   ),\r\n"
			+ "latest_effective_dates AS (SELECT cem.sc_emp_id,cem.employee_id , cem.first_name,cem.last_name, cem.sales_rep_id,cem.comm_plan_id,\r\n"
			+ "			            ccpm.comm_plan ,cem.supervisor_id , cem.effective_date, cem.user_role ,cem.user_type,  cem.sales_rep_channel ,cem.sales_rep_type ,  cem.soft_termination_date  , cem.profile_status ,\r\n"
			+ "			          LEAD(cem.effective_date) OVER (PARTITION BY cem.sc_emp_id ORDER BY cem.effective_date) AS next_effective_date "
			+ ",(select string_agg(c1.corp::varchar, ', ' order by c1.corp)  from c_employee_corp_reln c1 where c1.sc_emp_id =cem.sc_emp_id and c1.effective_date=cem.effective_date) asscCorps "
			+ "			       FROM  c_comm_plan_master ccpm ,c_employee_master cem\r\n"
			+ "			       left join c_employee_corp_reln cecr on( cecr.sc_emp_id  = cem.sc_emp_id and cecr.effective_date=cem.effective_date )\r\n"
			+ "			   where ccpm.comm_plan_id = cem.comm_plan_id\r\n"
			+ "			   and ccpm.effective_date =(select MAX(ccpm1.effective_date) from c_comm_plan_master ccpm1 where ccpm.comm_plan_id = ccpm1.comm_plan_id and ccpm1.effective_date <= current_date)\r\n"
			+ "			   and cem.comm_plan_id IS NOT NULL AND cem.effective_date IS NOT NULL\r\n"
			+ "			   group by cem.sc_emp_id,cem.employee_id,cem.first_name,cem.last_name,cem.sales_rep_id,cem.comm_plan_id,ccpm.comm_plan , cem.effective_date\r\n"
			+ "			   )\r\n"
			+ "SELECT e.sc_emp_id,e.name as empname,  e.sales_rep_id as Sales_rep_ID,e.comm_plan_id as comm_plan_id,e.effective_date as effective_date,e.edate,"
			+ "			   e.user_role as user_role,e.user_type as user_type,e.first_name,e.middle_name,e.last_name,\r\n"
			+ "			       e.sales_rep_type,to_char(e.soft_termination_date,'MM-DD-YYYY') softdate,e.soft_termination_date,e.profile_status,e.sales_rep_channel,\r\n"
			+ "			       e.sc_emp_id,e.network_id,e.email_address,e.calendar_type,e.created_by,e.created_dt,e.operator_id,e.supervisor_id ,e.supervisor_name ,e.employee_id,"
			+ "max(led.asscCorps) asscCorps,"
			+ "			       MAX(CASE WHEN led.effective_date::varchar < ? AND (led.next_effective_date IS NULL OR led.next_effective_date::varchar >= ?) THEN led.comm_plan ELSE NULL END) AS complan1,\r\n"
			+ "			       MAX(CASE WHEN led.effective_date::varchar < ? AND (led.next_effective_date IS NULL OR led.next_effective_date::varchar >= ?) THEN led.comm_plan ELSE NULL END) AS complan2,\r\n"
			+ "			       MAX(CASE WHEN led.effective_date::varchar < ? AND (led.next_effective_date IS NULL OR led.next_effective_date::varchar >= ?) THEN led.comm_plan ELSE NULL END) AS complan3,\r\n"
			+ "			   	   MAX(CASE WHEN led.effective_date::varchar < ? AND (led.next_effective_date IS NULL OR led.next_effective_date::varchar >= ?) THEN (select cem.first_name || ' ' || cem.last_name as empname from c_employee_master cem where employee_id =led.supervisor_id limit 1) ELSE NULL END) AS supname1,\r\n"
			+ "			       MAX(CASE WHEN led.effective_date::varchar < ? AND (led.next_effective_date IS NULL OR led.next_effective_date::varchar >= ?) THEN (select cem.first_name || ' ' || cem.last_name as empname from c_employee_master cem where employee_id =led.supervisor_id limit 1) ELSE NULL END) AS supname2,\r\n"
			+ "			       MAX(CASE WHEN led.effective_date::varchar < ? AND (led.next_effective_date IS NULL OR led.next_effective_date::varchar >= ?) THEN (select cem.first_name || ' ' || cem.last_name as empname from c_employee_master cem where employee_id =led.supervisor_id limit 1) ELSE NULL END) AS supname3\r\n"
			+ "			   FROM enrollments e\r\n"
			+ "			   LEFT JOIN latest_effective_dates led ON (e.sc_emp_id = led.sc_emp_id)\r\n"
			+ "			    where led.profile_status =? " + "and (1::varchar=? or lower(led.first_name) like lower(?)) "
			+ "and (1::varchar=? or lower(led.last_name) like lower(?))  "
			+ "and (1::varchar=? or lower(led.employee_id) like lower(?))  "
			+ "and (1::varchar=? or lower(led.sc_emp_id) like lower(?))  "
			+ "and (1::varchar=? or led.supervisor_id like ?)  "
			+ "and (1::varchar=? or lower(led.user_role) = lower(?))  "
			+ "and (1::varchar=? or lower(led.sales_rep_channel) = lower(?))  "
			+ "and (1::varchar=? or led.comm_plan_id = ?)  "
			+ "and (1::varchar=? or (led.effective_date::varchar <= ?)) "
			+ "			     GROUP BY e.sc_emp_id,e.name ,  e.sales_rep_id ,e.comm_plan_id ,e.effective_date,\r\n"
			+ "			   e.user_role,e.user_type,e.first_name,e.middle_name,e.last_name,\r\n"
			+ "			       e.sales_rep_type,e.soft_termination_date,e.profile_status,e.sales_rep_channel,\r\n"
			+ "			       e.sc_emp_id,e.network_id,e.email_address,e.calendar_type,e.created_by,e.created_dt,e.operator_id,e.supervisor_id ,e.supervisor_name ,e.employee_id,e.edate "
			+ "			     ORDER BY e.sc_emp_id";

	public final String GET_USER_BY_AS_OF_DATE = "WITH enrollments AS (  SELECT DISTINCT cem.sc_emp_id,cem.id,cem.first_name || ' ' || cem.last_name as name, cem.network_id ,cem.employee_id,"
			+ "cem.email_address,cem.calendar_type,cem.created_by,cem.created_dt,cem.operator_id\r\n"
			+ ", cem.comm_plan_id,cem.supervisor_ID,cem.user_role,cem.user_type,cem.first_name ,cem.middle_name,cem.last_name ,cem.soft_termination_date,cem.profile_status,cem.sales_rep_channel,cem.sales_rep_id,"
			+ "cem.effective_date,to_char(cem.effective_date,'MM-DD-YYYY') edate,"
			+ "cem.sales_rep_type,(SELECT concat(u2.first_name,',', u2.last_name  ,'-',u2.employee_id) FROM c_employee_master u2 where u2.employee_id  = cem.supervisor_id limit 1) supervisor_name,cem.commissionable "
			+ "FROM c_employee_master cem where cem.comm_plan_id IS NOT NULL AND cem.effective_date IS NOT null  "
			+ "			       and cem.employee_id=? and cem.effective_date::varchar = ? " + "			   ),"
			+ "latest_effective_dates AS (SELECT cem.sc_emp_id,cem.employee_id , cem.first_name,cem.last_name, cem.sales_rep_id,cem.comm_plan_id,\r\n"
			+ "			            ccpm.comm_plan ,cem.supervisor_id , cem.effective_date, cem.user_role ,cem.user_type,  cem.sales_rep_channel ,cem.sales_rep_type ,  cem.soft_termination_date  , cem.profile_status ,\r\n"
			+ "			          LEAD(cem.effective_date) OVER (PARTITION BY cem.sc_emp_id ORDER BY cem.effective_date) AS next_effective_date,cem.commissionable "
			+ "			       FROM  c_comm_plan_master ccpm ,c_employee_master cem\r\n"
			+ "			   where ccpm.comm_plan_id = cem.comm_plan_id\r\n"
			+ "			   and ccpm.effective_date =(select MAX(ccpm1.effective_date) from c_comm_plan_master ccpm1 where ccpm.comm_plan_id = ccpm1.comm_plan_id and ccpm1.effective_date <= current_date)\r\n"
			+ "			   and cem.comm_plan_id IS NOT NULL AND cem.effective_date IS NOT NULL and cem.employee_id=? and cem.effective_date::varchar = ? "
			+ "			   group by cem.sc_emp_id,cem.employee_id,cem.first_name,cem.last_name,cem.sales_rep_id,cem.comm_plan_id,ccpm.comm_plan , cem.effective_date "
			+ "			   )\r\n"
			+ "SELECT e.sc_emp_id,e.id,e.name as empname,  e.sales_rep_id as Sales_rep_ID,e.comm_plan_id as comm_plan_id,e.effective_date as effective_date,e.edate,"
			+ "			   e.user_role as user_role,e.user_type as user_type,e.first_name,e.middle_name,e.last_name,\r\n"
			+ "			       e.sales_rep_type,e.soft_termination_date,e.profile_status,e.sales_rep_channel,\r\n"
			+ "			       e.sc_emp_id,e.network_id,e.email_address,e.calendar_type,e.created_by,e.created_dt,e.operator_id,e.supervisor_id ,e.supervisor_name ,e.employee_id,e.commissionable "
			+ "			   FROM enrollments e"
			+ "			   LEFT JOIN latest_effective_dates led ON (e.sc_emp_id = led.sc_emp_id) "
			+ "			    where led.profile_status ='complete' and led.employee_id=? and led.effective_date::varchar=? "
			+ "GROUP BY e.sc_emp_id,e.id,e.name ,  e.sales_rep_id ,e.comm_plan_id ,e.effective_date,"
			+ "			   e.user_role,e.user_type,e.first_name,e.middle_name,e.last_name,"
			+ "			       e.sales_rep_type,e.soft_termination_date,e.profile_status,e.sales_rep_channel,"
			+ "			       e.sc_emp_id,e.network_id,e.email_address,e.calendar_type,e.created_by,e.created_dt,e.operator_id,e.supervisor_id ,e.supervisor_name ,e.employee_id,e.edate,e.commissionable "
			+ "			     ORDER BY e.sc_emp_id";

	public final String FIND_PROFILES_NEW = "WITH enrollments AS (  SELECT DISTINCT cem.sc_emp_id,cem.id,cem.first_name || ' ' || cem.last_name as name, cem.network_id ,cem.employee_id,"
			+ "cem.email_address,cem.calendar_type,cem.created_by,cem.created_dt,cem.operator_id\r\n"
			+ ", cem.comm_plan_id,cem.supervisor_ID,cem.user_role,cem.user_type,cem.first_name ,cem.middle_name,cem.last_name ,cem.soft_termination_date,cem.profile_status,cem.sales_rep_channel,cem.sales_rep_id,"
			+ "cem.effective_date,to_char(cem.effective_date,'MM-DD-YYYY') edate,"
			+ "cem.sales_rep_type,(SELECT concat(u2.first_name,',', u2.last_name  ,'-',u2.employee_id) FROM c_employee_master u2 where u2.employee_id  = cem.supervisor_id limit 1) supervisor_name,cem.commissionable "
			+ "FROM c_employee_master cem where cem.comm_plan_id IS NOT NULL AND cem.effective_date IS NOT null  "
			+ "			       and cem.effective_date = (select max(cem1.effective_date) from c_employee_master cem1 where cem.sc_emp_id = cem1.sc_emp_id and cem1.profile_status =? and cem1.effective_date <= current_date )\r\n"
			+ "			   ),\r\n"
			+ "latest_effective_dates AS (SELECT cem.sc_emp_id,cem.id,cem.employee_id , cem.first_name,cem.last_name, cem.sales_rep_id,cem.comm_plan_id,\r\n"
			+ "			            ccpm.comm_plan ,cem.supervisor_id , cem.effective_date, cem.user_role ,cem.user_type,  cem.sales_rep_channel ,cem.sales_rep_type ,  cem.soft_termination_date  , cem.profile_status ,\r\n"
			+ "			          LEAD(cem.effective_date) OVER (PARTITION BY cem.sc_emp_id ORDER BY cem.effective_date) AS next_effective_date "
			+ "			       FROM  c_comm_plan_master ccpm ,c_employee_master cem\r\n"
			+ "			   where ccpm.comm_plan_id = cem.comm_plan_id\r\n"
			+ "			   and ccpm.effective_date =(select MAX(ccpm1.effective_date) from c_comm_plan_master ccpm1 where ccpm.comm_plan_id = ccpm1.comm_plan_id and ccpm1.effective_date <= current_date)\r\n"
			+ "			   and cem.comm_plan_id IS NOT NULL AND cem.effective_date IS NOT NULL\r\n"
			+ "			   group by cem.sc_emp_id,cem.id,cem.employee_id,cem.first_name,cem.last_name,cem.sales_rep_id,cem.comm_plan_id,ccpm.comm_plan , cem.effective_date\r\n"
			+ "			   )\r\n"
			+ "SELECT e.sc_emp_id,e.id,e.name as empname,  e.sales_rep_id as Sales_rep_ID,e.comm_plan_id as comm_plan_id,e.effective_date as effective_date,e.edate,"
			+ "			   e.user_role as user_role,e.user_type as user_type,e.first_name,e.middle_name,e.last_name,\r\n"
			+ "			       e.sales_rep_type,to_char(e.soft_termination_date,'MM-DD-YYYY') softdate,e.soft_termination_date,e.profile_status,e.sales_rep_channel,\r\n"
			+ "			       e.sc_emp_id,e.network_id,e.email_address,e.calendar_type,e.created_by,e.created_dt,e.operator_id,e.supervisor_id ,e.supervisor_name ,e.employee_id,e.commissionable,"
			+ "			       MAX(CASE WHEN led.effective_date::varchar < ? AND (led.next_effective_date IS NULL OR led.next_effective_date::varchar >= ?) THEN led.comm_plan ELSE NULL END) AS complan1,\r\n"
			+ "			       MAX(CASE WHEN led.effective_date::varchar < ? AND (led.next_effective_date IS NULL OR led.next_effective_date::varchar >= ?) THEN led.comm_plan ELSE NULL END) AS complan2,\r\n"
			+ "			       MAX(CASE WHEN led.effective_date::varchar < ? AND (led.next_effective_date IS NULL OR led.next_effective_date::varchar >= ?) THEN led.comm_plan ELSE NULL END) AS complan3,\r\n"
			+ "			   	   MAX(CASE WHEN led.effective_date::varchar < ? AND (led.next_effective_date IS NULL OR led.next_effective_date::varchar >= ?) THEN (select cem.first_name || ' ' || cem.last_name as empname from c_employee_master cem where employee_id =led.supervisor_id limit 1) ELSE NULL END) AS supname1,\r\n"
			+ "			       MAX(CASE WHEN led.effective_date::varchar < ? AND (led.next_effective_date IS NULL OR led.next_effective_date::varchar >= ?) THEN (select cem.first_name || ' ' || cem.last_name as empname from c_employee_master cem where employee_id =led.supervisor_id limit 1) ELSE NULL END) AS supname2,\r\n"
			+ "			       MAX(CASE WHEN led.effective_date::varchar < ? AND (led.next_effective_date IS NULL OR led.next_effective_date::varchar >= ?) THEN (select cem.first_name || ' ' || cem.last_name as empname from c_employee_master cem where employee_id =led.supervisor_id limit 1) ELSE NULL END) AS supname3\r\n"
			+ "			   FROM enrollments e\r\n"
			+ "			   LEFT JOIN latest_effective_dates led ON (e.sc_emp_id = led.sc_emp_id)\r\n"
			+ "			    where led.profile_status =? " + "and (1::varchar=? or lower(led.first_name) like lower(?)) "
			+ "and (1::varchar=? or lower(led.last_name) like lower(?))  "
			+ "and (1::varchar=? or lower(led.employee_id) like lower(?))  "
			+ "and (1::varchar=? or lower(led.sc_emp_id) like lower(?))  "
			+ "and (1::varchar=? or led.supervisor_id like ?)  "
			+ "and (1::varchar=? or lower(led.user_role) = lower(?))  "
			+ "and (1::varchar=? or lower(led.sales_rep_channel) = lower(?))  "
			+ "and (1::varchar=? or led.comm_plan_id = ?)  "
			+ "and (1::varchar=? or (led.effective_date::varchar <= ?)) "
			+ "			     GROUP BY e.sc_emp_id,e.id,e.name ,  e.sales_rep_id ,e.comm_plan_id ,e.effective_date,\r\n"
			+ "			   e.user_role,e.user_type,e.first_name,e.middle_name,e.last_name,\r\n"
			+ "			       e.sales_rep_type,e.soft_termination_date,e.profile_status,e.sales_rep_channel,\r\n"
			+ "			       e.sc_emp_id,e.network_id,e.email_address,e.calendar_type,e.created_by,e.created_dt,e.operator_id,e.supervisor_id ,e.supervisor_name ,e.employee_id,e.edate,e.commissionable "
			+ "			     ORDER BY e.sc_emp_id";
	
	public final String FIND_PROFILE_USERS = "WITH enrollments AS (  SELECT DISTINCT cem.sc_emp_id,cem.first_name || ' ' || cem.last_name as name, cem.network_id ,cem.employee_id,"
			+ "cem.email_address,cem.calendar_type,cem.created_by,cem.created_dt,cem.operator_id\r\n"
			+ ", cem.comm_plan_id,cem.supervisor_ID,cem.user_role,cem.user_type,cem.first_name ,cem.middle_name,cem.last_name ,cem.soft_termination_date,cem.profile_status,cem.sales_rep_channel,cem.sales_rep_id,"
			+ "cem.effective_date,to_char(cem.effective_date,'MM-DD-YYYY') edate,"
			+ "cem.sales_rep_type,(SELECT concat(u2.first_name,',', u2.last_name  ,'-',u2.employee_id) FROM c_employee_master u2 where u2.employee_id  = cem.supervisor_id limit 1) supervisor_name,cem.commissionable "
			+ "FROM c_employee_master cem where cem.comm_plan_id IS NOT NULL AND cem.effective_date IS NOT null  "
			+ "			       and cem.effective_date = (select max(cem1.effective_date) from c_employee_master cem1 where cem.sc_emp_id = cem1.sc_emp_id and cem1.profile_status ='complete' and cem1.effective_date <= current_date )\r\n"
			+ "			   ),\r\n"
			+ "latest_effective_dates AS (SELECT cem.sc_emp_id,cem.employee_id , cem.first_name,cem.last_name, cem.sales_rep_id,cem.comm_plan_id,\r\n"
			+ "			            ccpm.comm_plan ,cem.supervisor_id , cem.effective_date, cem.user_role ,cem.user_type,  cem.sales_rep_channel ,cem.sales_rep_type ,  cem.soft_termination_date  , cem.profile_status ,\r\n"
			+ "			          LEAD(cem.effective_date) OVER (PARTITION BY cem.sc_emp_id ORDER BY cem.effective_date) AS next_effective_date "
			+ "			       FROM  c_comm_plan_master ccpm ,c_employee_master cem\r\n"
			+ "			   where ccpm.comm_plan_id = cem.comm_plan_id\r\n"
			+ "			   and ccpm.effective_date =(select MAX(ccpm1.effective_date) from c_comm_plan_master ccpm1 where ccpm.comm_plan_id = ccpm1.comm_plan_id and ccpm1.effective_date <= current_date)\r\n"
			+ "			   and cem.comm_plan_id IS NOT NULL AND cem.effective_date IS NOT NULL\r\n"
			+ "			   group by cem.sc_emp_id,cem.employee_id,cem.first_name,cem.last_name,cem.sales_rep_id,cem.comm_plan_id,ccpm.comm_plan , cem.effective_date\r\n"
			+ "			   )\r\n"
			+ "SELECT e.sc_emp_id,e.name as empname,  e.sales_rep_id as Sales_rep_ID,e.comm_plan_id as comm_plan_id,e.effective_date as effective_date,e.edate,"
			+ "			   e.user_role as user_role,e.user_type as user_type,e.first_name,e.middle_name,e.last_name,\r\n"
			+ "			       e.sales_rep_type,e.soft_termination_date,e.profile_status,e.sales_rep_channel,\r\n"
			+ "			       e.sc_emp_id,e.network_id,e.email_address,e.calendar_type,e.created_by,e.created_dt,e.operator_id,e.supervisor_id ,e.supervisor_name ,e.employee_id,e.commissionable,"
			+ "			       MAX(CASE WHEN led.effective_date::varchar < ? AND (led.next_effective_date IS NULL OR led.next_effective_date::varchar >= ?) THEN led.comm_plan ELSE NULL END) AS complan1,\r\n"
			+ "			       MAX(CASE WHEN led.effective_date::varchar < ? AND (led.next_effective_date IS NULL OR led.next_effective_date::varchar >= ?) THEN led.comm_plan ELSE NULL END) AS complan2,\r\n"
			+ "			       MAX(CASE WHEN led.effective_date::varchar < ? AND (led.next_effective_date IS NULL OR led.next_effective_date::varchar >= ?) THEN led.comm_plan ELSE NULL END) AS complan3,\r\n"
			+ "			   	   MAX(CASE WHEN led.effective_date::varchar < ? AND (led.next_effective_date IS NULL OR led.next_effective_date::varchar >= ?) THEN (select cem.first_name || ' ' || cem.last_name as empname from c_employee_master cem where employee_id =led.supervisor_id limit 1) ELSE NULL END) AS supname1,\r\n"
			+ "			       MAX(CASE WHEN led.effective_date::varchar < ? AND (led.next_effective_date IS NULL OR led.next_effective_date::varchar >= ?) THEN (select cem.first_name || ' ' || cem.last_name as empname from c_employee_master cem where employee_id =led.supervisor_id limit 1) ELSE NULL END) AS supname2,\r\n"
			+ "			       MAX(CASE WHEN led.effective_date::varchar < ? AND (led.next_effective_date IS NULL OR led.next_effective_date::varchar >= ?) THEN (select cem.first_name || ' ' || cem.last_name as empname from c_employee_master cem where employee_id =led.supervisor_id limit 1) ELSE NULL END) AS supname3\r\n"
			+ "			   FROM enrollments e\r\n"
			+ "			   LEFT JOIN latest_effective_dates led ON (e.sc_emp_id = led.sc_emp_id)\r\n"
			+ "			    where led.profile_status =? " + "and (1::varchar=? or lower(led.first_name) like lower(?)) "
			+ "and (1::varchar=? or lower(led.last_name) like lower(?))  "
			+ "and (1::varchar=? or lower(led.employee_id) like lower(?))  "
			+ "and (1::varchar=? or lower(led.sc_emp_id) like lower(?))  "
			+ "and (1::varchar=? or led.supervisor_id like ?)  "
			+ "and (1::varchar=? or lower(led.user_role) = lower(?))  "
			+ "and (1::varchar=? or lower(led.sales_rep_channel) = lower(?))  "
			+ "and (1::varchar=? or led.comm_plan_id = ?)  "
			+ "and (1::varchar=? or (led.effective_date::varchar <= ?)) "
			+ "			     GROUP BY e.sc_emp_id,e.name ,  e.sales_rep_id ,e.comm_plan_id ,e.effective_date,\r\n"
			+ "			   e.user_role,e.user_type,e.first_name,e.middle_name,e.last_name,\r\n"
			+ "			       e.sales_rep_type,e.soft_termination_date,e.profile_status,e.sales_rep_channel,\r\n"
			+ "			       e.sc_emp_id,e.network_id,e.email_address,e.calendar_type,e.created_by,e.created_dt,e.operator_id,e.supervisor_id ,e.supervisor_name ,e.employee_id,e.edate,e.commissionable "
			+ "			     ORDER BY e.sc_emp_id";

	public final String USER_AS_OF_DATE = "select employee_id ,effective_date from c_employee_master cem  where employee_id = ? and profile_status='complete' order by effective_date desc";
	
	public final String FIND_PROFILES_ADMIN = "select cem.network_id,to_char(cem.effective_date,'MM-DD-YYYY') edate,cem.effective_date,"
			+ "first_name,middle_name,last_name,cem.created_by,cem.created_dt,employee_id,cem.sc_emp_id,cem.id,sales_rep_id,network_id,"
			+ "email_address,joining_date,work_status,to_char(soft_termination_date,'MM-DD-YYYY') softdate,soft_termination_date,supervisor_pref_name,pref_first_name,"
			+ "pref_last_name,profile_status,cem.comm_plan_id,user_type,user_role,sales_rep_channel,"
			+ "sales_rep_channel_desc,cem.calendar_type,"
			+ "(SELECT concat(u2.first_name,',', u2.last_name  ,'-',u2.employee_id) FROM c_employee_master u2 where u2.employee_id  = cem.supervisor_id limit 1) supervisor_name,"
			+ "supervisor_name supname,"
			+ "supervisor_id,operator_id,concat(TO_CHAR(cem.effective_date, 'YYYY/MM/DD'),'-',"
			+ "TO_CHAR(cem.soft_termination_date, 'YYYY/MM/DD')) activeCommPeriod ,ccpm.comm_plan,concat(cem.last_name,', ',first_name) as empname,sales_rep_type,ccpm.sales_channel_desc,"
			+ "(select string_agg(c1.corp::varchar, ', ' order by c1.corp)  from c_employee_corp_reln c1 where c1.sc_emp_id =cem.sc_emp_id and c1.effective_date=cem.effective_date) asscCorps  "
			+ "from c_employee_master cem "
			+ "left join c_employee_corp_reln cecr  on (cecr.sc_emp_id  = cem.sc_emp_id and cecr.effective_date=cem.effective_date) "
			+ "left join c_comm_plan_master ccpm on (cem.comm_plan_id = ccpm.comm_plan_id)  "
			+ "left join c_comm_calendar ccc  on (ccc.calendar_type  = cem.calendar_type and ccc.calendar_type=ccpm.calendar_type) "
			+ "where profile_status =? " + "and (1::varchar=? or lower(cem.first_name) like lower(?)) "
			+ "and (1::varchar=? or lower(cem.last_name) like lower(?)) "
			+ "and (1::varchar=? or lower(cem.employee_id) like lower(?)) "
			+ "and (1::varchar=? or lower(cem.sc_emp_id) like lower(?)) "
			+ "and (1::varchar=? or cem.supervisor_id like ?) "
			+ "and (1::varchar=? or lower(cem.user_type) = lower(?)) "
			+ "and (1::varchar=? or lower(cem.sales_rep_channel) = lower(?)) "
			+ "and (1::varchar=? or ccpm.comm_plan_id = ?) "
			+ "and (1::varchar=? or (cem.effective_date::varchar <= ?)) "
			+ "group by network_id ,cem.effective_date,first_name,middle_name,last_name,cem.created_by,cem.created_dt,employee_id,cem.sc_emp_id,cem.id,sales_rep_id,"
			+ "email_address,joining_date,work_status,soft_termination_date,supervisor_pref_name,pref_first_name,"
			+ "pref_last_name,profile_status,cem.comm_plan_id,user_type,user_role,sales_rep_channel,"
			+ "sales_rep_channel_desc,cem.calendar_type,supervisor_id,supervisor_name,operator_id,ccpm.comm_plan,sales_rep_type,ccpm.sales_channel_desc  "
			+ "order by cem.effective_date desc";

	public final String FIND_PROFILES_PENDING = "select concat(cem.last_name,', ',first_name) as empname,"
			+ "(SELECT concat(u2.first_name,',', u2.last_name  ,'-',u2.employee_id) FROM c_employee_master u2 where u2.employee_id  = cem.supervisor_id limit 1) supervisor_name,* "
			+ "from c_employee_master cem "
			+ "where profile_status =? "
			+ "and (1::varchar=? or lower(cem.first_name) like lower(?)) "
			+ "and (1::varchar=? or lower(cem.last_name) like lower(?)) "
			+ "and (1::varchar=? or lower(cem.employee_id) like lower(?)) "
			+ "and (1::varchar=? or lower(cem.sc_emp_id) like lower(?))";

	public final String FIND_PROFILES_NEW1 = "WITH enrollments AS ( SELECT DISTINCT cem.sc_emp_id, cem.network_id ,cem.employee_id,cem.email_address,cem.calendar_type,cem.created_by,cem.created_dt,cem.operator_id ,"
			+ "(SELECT concat(u2.first_name,',', u2.last_name  ,'-',u2.employee_id) FROM c_employee_master u2 where u2.employee_id  = cem.supervisor_id limit 1) supervisor_name FROM c_employee_master cem "
			+ "    where cem.comm_plan_id IS NOT NULL AND cem.effective_date IS NOT null order by cem.employee_id "
			+ "), latest_effective_dates AS (SELECT cem.sc_emp_id,cem.employee_id , cem.first_name,cem.last_name,cem.first_name || ' ' || cem.last_name as name, cem.sales_rep_id,cem.comm_plan_id,"
			+ "         ccpm.comm_plan ,cem.supervisor_id , cem.effective_date,to_char(cem.effective_date,'MM-DD-YYYY') edate, cem.user_role ,cem.user_type,  cem.sales_rep_channel ,cem.sales_rep_type ,  cem.soft_termination_date  , cem.profile_status  ,"
			+ "        (select string_agg(c1.corp::varchar, ', ' order by c1.corp)  from c_employee_corp_reln c1 where c1.sc_emp_id =cem.sc_emp_id and c1.effective_date=cem.effective_date) asscCorps,"
			+ "        LEAD(cem.effective_date) OVER (PARTITION BY cem.sc_emp_id ORDER BY cem.effective_date) AS next_effective_date "
			+ "    FROM  c_comm_plan_master ccpm ,c_employee_master cem "
			+ "    left join c_employee_corp_reln cecr on( cecr.sc_emp_id  = cem.sc_emp_id and cecr.effective_date=cem.effective_date ) "
			+ "where ccpm.comm_plan_id = cem.comm_plan_id "
			+ "and ccpm.effective_date =(select MAX(ccpm1.effective_date) from c_comm_plan_master ccpm1 where ccpm.comm_plan_id = ccpm1.comm_plan_id and ccpm1.effective_date<=cem.effective_date) "
			+ "and cem.comm_plan_id IS NOT NULL AND cem.effective_date IS NOT NULL "
			+ "group by cem.sc_emp_id,cem.employee_id,cem.first_name,cem.last_name,cem.sales_rep_id,cem.comm_plan_id,ccpm.comm_plan , cem.effective_date) "
			+ "SELECT distinct on(e.sc_emp_id) e.sc_emp_id,MAX(led.name) as empname,e.sc_emp_id,e.network_id,e.email_address,e.calendar_type,e.created_by,e.created_dt,e.operator_id ,e.supervisor_name ,"
			+ "e.employee_id,max(led.sales_rep_id) as Sales_rep_ID,max(led.comm_plan_id) as comm_plan_id,max(led.effective_date) as effective_date,max(led.edate) as edate,"
			+ "max(led.user_role) as user_role,max(led.user_type) as user_type,max(led.first_name) as first_name,max(led.last_name) as last_name,"
			+ "    max(led.sales_rep_type) as sales_rep_type,max(led.soft_termination_date) as soft_termination_date,max(led.profile_status) as profile_status,max(led.sales_rep_channel) as sales_rep_channel,"
			+ "max(led.asscCorps) as asscCorps,"
			+ "    MAX(CASE WHEN led.effective_date::varchar < ? AND (led.next_effective_date IS NULL OR led.next_effective_date::varchar >= ?) THEN led.comm_plan ELSE NULL END) AS complan1,"
			+ "    MAX(CASE WHEN led.effective_date::varchar < ? AND (led.next_effective_date IS NULL OR led.next_effective_date::varchar >= ?) THEN led.comm_plan ELSE NULL END) AS complan2,"
			+ "    MAX(CASE WHEN led.effective_date::varchar < ? AND (led.next_effective_date IS NULL OR led.next_effective_date::varchar >= ?) THEN led.comm_plan ELSE NULL END) AS complan3,"
			+ "	   MAX(CASE WHEN led.effective_date::varchar < ? AND (led.next_effective_date IS NULL OR led.next_effective_date::varchar >= ?) THEN (select cem.first_name || ' ' || cem.last_name as empname from c_employee_master cem where employee_id =led.supervisor_id limit 1) ELSE NULL END) AS supname1,"
			+ "    MAX(CASE WHEN led.effective_date::varchar < ? AND (led.next_effective_date IS NULL OR led.next_effective_date::varchar >= ?) THEN (select cem.first_name || ' ' || cem.last_name as empname from c_employee_master cem where employee_id =led.supervisor_id limit 1) ELSE NULL END) AS supname2,"
			+ "    MAX(CASE WHEN led.effective_date::varchar < ? AND (led.next_effective_date IS NULL OR led.next_effective_date::varchar >= ?) THEN (select cem.first_name || ' ' || cem.last_name as empname from c_employee_master cem where employee_id =led.supervisor_id limit 1) ELSE NULL END) AS supname3 "
			+ "FROM enrollments e " + "LEFT JOIN latest_effective_dates led ON (e.sc_emp_id = led.sc_emp_id)   "
			+ "where led.profile_status =? " + "and (1::varchar=? or lower(led.first_name) like lower(?)) "
			+ "and (1::varchar=? or lower(led.last_name) like lower(?))  "
			+ "and (1::varchar=? or lower(led.employee_id) like lower(?))  "
			+ "and (1::varchar=? or lower(led.sc_emp_id) like lower(?))  "
			+ "and (1::varchar=? or led.supervisor_id like ?)  "
			+ "and (1::varchar=? or lower(led.user_role) = lower(?))  "
			+ "and (1::varchar=? or lower(led.sales_rep_channel) = lower(?))  "
			+ "and (1::varchar=? or led.comm_plan_id = ?)  "
			+ "and (1::varchar=? or (led.effective_date::varchar <= ?)) "
			+ "GROUP BY e.sc_emp_id,e.network_id ,e.employee_id,e.email_address,e.calendar_type,e.created_by,e.created_dt,e.operator_id ,e.supervisor_name ORDER BY e.sc_emp_id";

	public final String FIND_PROFILES = "select DISTINCT ON(cem.effective_date) cem.effective_date,cem.network_id,to_char(cem.effective_date,'MM-DD-YYYY') edate,cem.effective_date,"
			+ "first_name,middle_name,last_name,cem.created_by,cem.created_dt,employee_id,cem.sc_emp_id,sales_rep_id,network_id,"
			+ "email_address,joining_date,work_status,to_char(soft_termination_date,'MM-DD-YYYY') softdate,soft_termination_date,supervisor_pref_name,pref_first_name,"
			+ "pref_last_name,profile_status,cem.comm_plan_id,user_type,user_role,sales_rep_channel,"
			+ "sales_rep_channel_desc,cem.calendar_type,"
			+ "(SELECT concat(u2.first_name,',', u2.last_name  ,'-',u2.employee_id) FROM c_employee_master u2 where u2.employee_id  = cem.supervisor_id limit 1) supervisor_name,"
			+ "supervisor_name supname,"
			+ "supervisor_id,operator_id,concat(TO_CHAR(cem.effective_date, 'YYYY/MM/DD'),'-',"
			+ "TO_CHAR(cem.soft_termination_date, 'YYYY/MM/DD')) activeCommPeriod ,ccpm.comm_plan,concat(cem.last_name,', ',first_name) as empname,sales_rep_type,ccpm.sales_channel_desc,"
			+ "(select string_agg(c1.corp::varchar, ', ' order by c1.corp)  from c_employee_corp_reln c1 where c1.sc_emp_id =cem.sc_emp_id and c1.effective_date=cem.effective_date) asscCorps  "
			+ "from c_employee_master cem "
			+ "left join c_employee_corp_reln cecr  on (cecr.sc_emp_id  = cem.sc_emp_id and cecr.effective_date=cem.effective_date) "
			+ "left join c_comm_plan_master ccpm on (cem.comm_plan_id = ccpm.comm_plan_id)  "
			+ "left join c_comm_calendar ccc  on (ccc.calendar_type  = cem.calendar_type and ccc.calendar_type=ccpm.calendar_type) "
			+ "where profile_status =? " + "and (1::varchar=? or lower(cem.first_name) like lower(?)) "
			+ "and (1::varchar=? or lower(cem.last_name) like lower(?)) "
			+ "and (1::varchar=? or lower(cem.employee_id) like lower(?)) "
			+ "and (1::varchar=? or lower(cem.sc_emp_id) like lower(?)) "
			+ "and (1::varchar=? or cem.supervisor_id like ?) "
			+ "and (1::varchar=? or lower(cem.user_type) = lower(?)) "
			+ "and (1::varchar=? or lower(cem.sales_rep_channel) = lower(?)) "
			+ "and (1::varchar=? or ccpm.comm_plan_id = ?) "
			+ "and (1::varchar=? or (cem.effective_date::varchar between ? and ?)) "
			+ "group by network_id ,cem.effective_date,first_name,middle_name,last_name,cem.created_by,cem.created_dt,employee_id,cem.sc_emp_id,sales_rep_id,"
			+ "email_address,joining_date,work_status,soft_termination_date,supervisor_pref_name,pref_first_name,"
			+ "pref_last_name,profile_status,cem.comm_plan_id,user_type,user_role,sales_rep_channel,"
			+ "sales_rep_channel_desc,cem.calendar_type,supervisor_id,supervisor_name,operator_id,ccpm.comm_plan,sales_rep_type,ccpm.sales_channel_desc  "
			+ "order by cem.effective_date desc";

	public final String FIND_PROFILES_REPORT = "select DISTINCT ON(cem.network_id) network_id,to_char(cem.effective_date,'MM-DD-YYYY') edate,cem.effective_date,"
			+ "first_name,middle_name,last_name,cem.created_by,cem.created_dt,employee_id,cem.sc_emp_id,sales_rep_id,network_id,"
			+ "email_address,joining_date,work_status,to_char(soft_termination_date,'MM-DD-YYYY') softdate,soft_termination_date,supervisor_pref_name,pref_first_name,"
			+ "pref_last_name,profile_status,cem.comm_plan_id,user_type,user_role,sales_rep_channel,"
			+ "sales_rep_channel_desc,cem.calendar_type,"
//			+ "concat(supervisor_name,'-',supervisor_id) supervisor_name,"
			+ "(SELECT concat(u2.first_name,',', u2.last_name  ,'-',u2.employee_id) FROM c_employee_master u2 where u2.employee_id  = cem.supervisor_id limit 1) supervisor_name,"
			+ "supervisor_name supname,"
			+ "supervisor_id,operator_id,concat(TO_CHAR(cem.effective_date, 'YYYY/MM/DD'),'-',"
			+ "TO_CHAR(cem.soft_termination_date, 'YYYY/MM/DD')) activeCommPeriod ,ccpm.comm_plan,concat(cem.last_name,', ',first_name) as empname,sales_rep_type,ccpm.sales_channel_desc,"
			+ "(select string_agg(c1.corp::varchar, ', ' order by c1.corp)  from c_employee_corp_reln c1 where c1.sc_emp_id =cem.sc_emp_id) asscCorps  "
			+ "from c_employee_master cem "
			+ "left join c_comm_plan_master ccpm on (cem.comm_plan_id = ccpm.comm_plan_id)  "
			+ "left join c_comm_calendar ccc  on (ccc.calendar_type  = cem.calendar_type and ccc.calendar_type=ccpm.calendar_type) "
			+ "left join c_employee_corp_reln cecr  on (cecr.sc_emp_id  = cem.sc_emp_id) " + "where profile_status =? "
			+ "and (1::varchar=? or lower(cem.first_name) like lower(?)) "
			+ "and (1::varchar=? or lower(cem.last_name) like lower(?)) "
			+ "and (1::varchar=? or lower(cem.employee_id) like lower(?)) "
			+ "and (1::varchar=? or lower(cem.sc_emp_id) like lower(?)) "
			+ "and (1::varchar=? or cem.supervisor_id like ?) "
			+ "and (1::varchar=? or lower(cem.user_type) = lower(?)) "
			+ "and (1::varchar=? or lower(cem.sales_rep_channel) = lower(?)) "
			+ "and (1::varchar=? or ccpm.comm_plan_id = ?) "
			+ "and (1::varchar=? or (cem.effective_date::varchar <= ?)) "
			+ "and cem.effective_date = (select max(cem1.effective_date) from c_employee_master cem1 where cem.id = cem1.id  and cem1.effective_date <=(SELECT CURRENT_DATE)) "
			+ "and ccpm.effective_date = (select max(ccpm1.effective_date) from c_comm_plan_master ccpm1 where ccpm.comm_plan_id = ccpm1.comm_plan_id  and ccpm1.effective_date <=(SELECT CURRENT_DATE))  "
			+ "group by network_id ,cem.effective_date,first_name,middle_name,last_name,cem.created_by,cem.created_dt,employee_id,cem.sc_emp_id,sales_rep_id,"
			+ "email_address,joining_date,work_status,soft_termination_date,supervisor_pref_name,pref_first_name,"
			+ "pref_last_name,profile_status,cem.comm_plan_id,user_type,user_role,sales_rep_channel,"
			+ "sales_rep_channel_desc,cem.calendar_type,supervisor_id,supervisor_name,operator_id,ccpm.comm_plan,sales_rep_type,ccpm.sales_channel_desc  "
			+ "order by cem.network_id,cem.effective_date desc";

	

	public final String FIND_PENDING_PROFILES1 = "select DISTINCT ON(cem.network_id) network_id,to_char(cem.effective_date,'MM-DD-YYYY') edate,cem.effective_date,"
			+ "first_name,middle_name,last_name,cem.created_by,cem.created_dt,employee_id,sc_emp_id,sales_rep_id,network_id,"
			+ "email_address,joining_date,work_status,to_char(soft_termination_date,'MM-DD-YYYY') softdate,soft_termination_date,supervisor_pref_name,pref_first_name,"
			+ "pref_last_name,profile_status,cem.comm_plan_id,user_type,user_role,sales_rep_channel,"
			+ "sales_rep_channel_desc,cem.calendar_type,concat(supervisor_name,'-',supervisor_id) supervisor_name,supervisor_name supname,"
			+ "supervisor_id,operator_id,concat(TO_CHAR(cem.effective_date, 'YYYY/MM/DD'),'-',"
			+ "TO_CHAR(cem.soft_termination_date, 'YYYY/MM/DD')) activeCommPeriod ,ccpm.comm_plan,concat(cem.last_name,', ',first_name) as empname,sales_rep_type,ccpm.sales_channel_desc "
			+ "from c_employee_master cem "
			+ "left join c_comm_plan_master ccpm on (cem.comm_plan_id = ccpm.comm_plan_id)  "
			+ "where profile_status =? " + "and (1::varchar=? or lower(cem.first_name) like lower(?)) "
			+ "and (1::varchar=? or lower(cem.last_name) like lower(?)) "
			+ "and (1::varchar=? or lower(cem.employee_id) like lower(?)) "
			+ "and (1::varchar=? or lower(cem.sc_emp_id) like lower(?)) "
			+ "and (1::varchar=? or cem.supervisor_id like ?) "
			+ "and (1::varchar=? or lower(cem.user_type) = lower(?)) "
			+ "and (1::varchar=? or lower(cem.sales_rep_channel) = lower(?)) "
			+ "and (1::varchar=? or ccpm.comm_plan_id = ?) "
			+ "and cem.effective_date = (select max(cem1.effective_date) from c_employee_master cem1 where cem.id = cem1.id  and cem1.effective_date <=(SELECT CURRENT_DATE)) "
			+ "group by network_id ,cem.effective_date,first_name,middle_name,last_name,cem.created_by,cem.created_dt,employee_id,sc_emp_id,sales_rep_id,"
			+ "email_address,joining_date,work_status,soft_termination_date,supervisor_pref_name,pref_first_name,"
			+ "pref_last_name,profile_status,cem.comm_plan_id,user_type,user_role,sales_rep_channel,"
			+ "sales_rep_channel_desc,cem.calendar_type,supervisor_id,supervisor_name,operator_id,ccpm.comm_plan,sales_rep_type,ccpm.sales_channel_desc  "
			+ "order by cem.network_id,cem.effective_date desc";

	public final String FIND_COMPLETED_PROFILES = "select DISTINCT ON(cem.network_id) network_id,to_char(cem.effective_date,'MM-DD-YYYY') edate,cem.effective_date,"
			+ "first_name,middle_name,last_name,cem.created_by,cem.created_dt,employee_id,sc_emp_id,sales_rep_id,network_id,"
			+ "email_address,joining_date,work_status,to_char(soft_termination_date,'MM-DD-YYYY') softdate,soft_termination_date,supervisor_pref_name,pref_first_name,"
			+ "pref_last_name,profile_status,cem.comm_plan_id,user_type,user_role,sales_rep_channel,"
			+ "sales_rep_channel_desc,cem.calendar_type,concat(supervisor_name,'-',supervisor_id) supervisor_name,"
			+ "supervisor_id,operator_id,concat(TO_CHAR(cem.effective_date, 'YYYY/MM/DD'),'-',"
			+ "TO_CHAR(cem.soft_termination_date, 'YYYY/MM/DD')) activeCommPeriod ,ccpm.comm_plan,concat(cem.last_name,', ',first_name,', ',middle_name) as empname,sales_rep_type,ccpm.sales_channel_desc "
			+ "from c_employee_master cem "
			+ "left join c_comm_plan_master ccpm on (cem.comm_plan_id = ccpm.comm_plan_id)  "
			+ "where profile_status ='complete' " + "and (1::varchar=? or lower(cem.first_name) = lower(?)) "
			+ "and (1::varchar=? or lower(cem.last_name) = lower(?)) "
			+ "and (1::varchar=? or lower(cem.employee_id) = lower(?)) "
			+ "and (1::varchar=? or lower(cem.sc_emp_id) = lower(?)) " + "and (1::varchar=? or cem.supervisor_id = ?) "
			+ "and (1::varchar=? or lower(cem.user_type) = lower(?)) "
			+ "and (1::varchar=? or lower(cem.sales_rep_channel) = lower(?)) "
			+ "and (1::varchar=? or ccpm.comm_plan_id = ?) "
			+ "group by network_id ,cem.effective_date,first_name,middle_name,last_name,cem.created_by,cem.created_dt,employee_id,sc_emp_id,sales_rep_id,"
			+ "email_address,joining_date,work_status,soft_termination_date,supervisor_pref_name,pref_first_name,"
			+ "pref_last_name,profile_status,cem.comm_plan_id,user_type,user_role,sales_rep_channel,"
			+ "sales_rep_channel_desc,cem.calendar_type,supervisor_id,supervisor_name,operator_id,ccpm.comm_plan,sales_rep_type,ccpm.sales_channel_desc  "
			+ "order by cem.network_id,cem.effective_date desc";

	public final String FIND_PENDING_PROFILES = "select DISTINCT ON(cem.network_id) network_id,cem.effective_date ,first_name,middle_name,"
			+ "last_name,cem.created_by,cem.created_dt,employee_id,sc_emp_id,sales_rep_id,network_id,\r\n"
			+ "email_address,joining_date,work_status,soft_termination_date,supervisor_pref_name,pref_first_name,\r\n"
			+ "pref_last_name,profile_status,cem.comm_plan_id,user_type,user_role,sales_rep_channel,\r\n"
			+ "sales_rep_channel_desc,cem.calendar_type,concat(supervisor_name,'-',supervisor_id) supervisor_name,supervisor_id,operator_id,\r\n"
			+ "concat(TO_CHAR(cem.effective_date, 'YYYY/MM/DD'),'-',\r\n"
			+ "TO_CHAR(cem.soft_termination_date, 'YYYY/MM/DD')) activeCommPeriod ,ccpm.comm_plan,concat(cem.last_name,', ',first_name,', ',middle_name) as empname,sales_rep_type,ccpm.sales_channel_desc "
			+ "from c_employee_master cem \r\n"
			+ "left join c_comm_plan_master ccpm on (cem.comm_plan_id = ccpm.comm_plan_id)  \r\n"
			+ "where profile_status in ('pending') \r\n"
			+ "group by network_id ,cem.effective_date,first_name,middle_name,last_name,cem.created_by,cem.created_dt,employee_id,sc_emp_id,sales_rep_id,\r\n"
			+ "email_address,joining_date,work_status,soft_termination_date,supervisor_pref_name,pref_first_name,\r\n"
			+ "pref_last_name,profile_status,cem.comm_plan_id,user_type,user_role,sales_rep_channel,\r\n"
			+ "sales_rep_channel_desc,cem.calendar_type,supervisor_id,supervisor_name,operator_id,ccpm.comm_plan,sales_rep_type,ccpm.sales_channel_desc  "
			+ "order by cem.network_id,cem.effective_date desc";

	public final String FIND_INACTIVE_PROFILES = "select *,concat(TO_CHAR(cem.effective_date, 'YYYY/MM/DD'),'-',"
			+ "TO_CHAR(cem.soft_termination_date, 'YYYY/MM/DD')) activeCommPeriod ,ccpm.comm_plan,concat(cem.last_name,', ',first_name,', ',middle_name) as empname "
			+ "from c_employee_master cem "
			+ "left join c_comm_plan_master ccpm on cem.comm_plan_id = ccpm.comm_plan_id "
			+ "	where cem.profile_status in ('inactive','pending') order by sc_emp_id";

	public final String FIND_COMPLETED_PROFILES_BY_DATE = "select *,concat(TO_CHAR(cem.effective_date, 'YYYY/MM/DD'),'-',"
			+ "TO_CHAR(cem.soft_termination_date, 'YYYY/MM/DD')) activeCommPeriod ,ccpm.comm_plan,concat(cem.last_name,', ',first_name,', ',middle_name) as empname "
			+ "from c_employee_master cem "
			+ "left join c_comm_plan_master ccpm on cem.comm_plan_id = ccpm.comm_plan_id "
			+ "	where cem.profile_status = 'complete' and cem.effective_date::varchar <= ? order by sc_emp_id ";

	public final String DOWNLOAD_USER_COMMPLAN_ASSIGNMENTS = "WITH enrollments AS (    SELECT         DISTINCT cem.sc_emp_id    FROM         c_employee_master cem    WHERE        cem.comm_plan_id IS NOT NULL        AND cem.effective_date IS NOT NULL "
			+ "), latest_effective_dates AS (    SELECT         cem.sc_emp_id,        cem.first_name || ' ' || cem.last_name as name,        cem.sales_rep_id,        cem.comm_plan_id, "
			+ "         ccpm.comm_plan_desc,        cem.effective_date,        LEAD(cem.effective_date) OVER (PARTITION BY cem.sc_emp_id ORDER BY cem.effective_date) AS next_effective_date "
			+ "    FROM         c_employee_master cem, c_comm_plan_master ccpm where ccpm.comm_plan_id = cem.comm_plan_id "
			+ "and ccpm.effective_date =(select MAX(ccpm1.effective_date) from c_comm_plan_master ccpm1 where ccpm.comm_plan_id = ccpm1.comm_plan_id and ccpm1.effective_date<=cem.effective_date) "
			+ "and        cem.comm_plan_id IS NOT NULL         AND cem.effective_date IS NOT NULL) "
			+ "SELECT     e.sc_emp_id,MAX(led.name) as Name,max(led.sales_rep_id) as Sales_rep_ID, "
			+ "    MAX(CASE WHEN led.effective_date < '2024-02-01' AND (led.next_effective_date IS NULL OR led.next_effective_date >= '2024-02-01') THEN led.comm_plan_desc ELSE NULL END) AS Jan, "
			+ "    MAX(CASE WHEN led.effective_date < '2024-03-01' AND (led.next_effective_date IS NULL OR led.next_effective_date >= '2024-03-01') THEN led.comm_plan_desc ELSE NULL END) AS Feb, "
			+ "    MAX(CASE WHEN led.effective_date < '2024-04-01' AND (led.next_effective_date IS NULL OR led.next_effective_date >= '2024-04-01') THEN led.comm_plan_desc ELSE NULL END) AS Mar, "
			+ "    MAX(CASE WHEN led.effective_date < '2024-05-01' AND (led.next_effective_date IS NULL OR led.next_effective_date >= '2024-05-01') THEN led.comm_plan_desc ELSE NULL END) AS Apr, "
			+ "    MAX(CASE WHEN led.effective_date < '2024-06-01' AND (led.next_effective_date IS NULL OR led.next_effective_date >= '2024-06-01') THEN led.comm_plan_desc ELSE NULL END) AS May, "
			+ "    MAX(CASE WHEN led.effective_date < '2024-07-01' AND (led.next_effective_date IS NULL OR led.next_effective_date >= '2024-07-01') THEN led.comm_plan_desc ELSE NULL END) AS Jun, "
			+ "    MAX(CASE WHEN led.effective_date < '2024-08-01' AND (led.next_effective_date IS NULL OR led.next_effective_date >= '2024-08-01') THEN led.comm_plan_desc ELSE NULL END) AS Jul "
			+ "FROM  enrollments e LEFT JOIN    latest_effective_dates led ON e.sc_emp_id = led.sc_emp_id "
			+ "GROUP BY    e.sc_emp_id ORDER BY     e.sc_emp_id";

	public final String FIND_ASSC_CORPS = "select * from (select sc_emp_id, corp, valid_from_dt, rank() over(partition by cecr.sc_emp_id order by cecr.valid_from_dt desc) "
			+ "rnk from c_employee_corp_reln cecr  order by cecr.sc_emp_id) as qq where rnk=1 ";

	public final String GET_SALES_REP_TYPES = "select description from c_translate_master ctm  where field_name ='Sales Rep Type' and effective_status='Y' order by description";
}
